-- Run this in Supabase Dashboard > SQL Editor

-- 1. BRANDS
create table if not exists brands (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamptz default now()
);

-- 2. DEVICE TYPES
create table if not exists device_types (
  id bigint generated by default as identity primary key,
  brand_id bigint references brands(id) on delete cascade,
  name text not null,
  created_at timestamptz default now(),
  unique (brand_id, name)
);

-- 3. PRODUCTS (devices)
create table if not exists products (
  id bigint generated by default as identity primary key,
  model_name text not null,
  type_id bigint references device_types(id),
  brand_id bigint references brands(id),
  purchase_date date,
  purchase_date_precision text default 'exact' check (purchase_date_precision in ('exact', 'year_only', 'unknown')),
  purchase_price numeric,
  has_bill boolean default false,
  bill_photo_path text,
  invoice_photo_path text,
  warranty_period_months integer,
  warranty_expiry_date date,
  seller text,
  serial_number text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- 4. SERVICE LOGS
create table if not exists service_logs (
  id bigint generated by default as identity primary key,
  product_id bigint references products(id) on delete cascade,
  note text,
  cost numeric,
  repairman_name text,
  repairman_contact text,
  vendor_name text,
  date date,
  date_precision text default 'exact' check (date_precision in ('exact', 'year_only', 'unknown')),
  day text,
  time text,
  photo_url text,
  next_service_due date,
  payment_mode text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- 5. REMINDERS
create table if not exists reminders (
  id bigint generated by default as identity primary key,
  product_id bigint references products(id) on delete cascade,
  type text not null,
  trigger_date date not null,
  notified boolean default false,
  created_at timestamptz default now()
);

-- INDEXES
create index if not exists idx_products_brand on products(brand_id);
create index if not exists idx_products_type on products(type_id);
create index if not exists idx_service_logs_product on service_logs(product_id);
create index if not exists idx_service_logs_date on service_logs(date desc);
create index if not exists idx_reminders_date on reminders(trigger_date);
create index if not exists idx_reminders_notified on reminders(notified);

-- RLS (enable for production, open for dev)
alter table brands enable row level security;
alter table device_types enable row level security;
alter table products enable row level security;
alter table service_logs enable row level security;
alter table reminders enable row level security;

-- Dev policies - allow all
create policy "public read brands" on brands for select using (true);
create policy "public write brands" on brands for all using (true) with check (true);

create policy "public read device_types" on device_types for select using (true);
create policy "public write device_types" on device_types for all using (true) with check (true);

create policy "public read products" on products for select using (true);
create policy "public write products" on products for all using (true) with check (true);

create policy "public read service_logs" on service_logs for select using (true);
create policy "public write service_logs" on service_logs for all using (true) with check (true);

create policy "public read reminders" on reminders for select using (true);
create policy "public write reminders" on reminders for all using (true) with check (true);

-- SEED BRANDS
insert into brands (name) values 
  ('LG'), ('Samsung'), ('Sony'), ('Whirlpool'), ('Voltas'), ('Daikin'),
  ('Blue Star'), ('Hitachi'), ('Carrier'), ('Panasonic'), ('Godrej'),
  ('Haier'), ('Bosch'), ('Siemens'), ('Videocon'), ('Kelvinator'),
  ('IFB'), ('Morphy Richards'), ('Bajaj'), ('Prestige'), ('Kaff'),
  ('Kent'), ('Aquaguard'), ('Pureit'), ('Livpure'), ('Havells'),
  ('AO Smith'), ('Eureka Forbes'), ('Tata Swach'), ('HUL'),
  ('Racold'), ('Venus'), ('V-Guard'), ('Crompton'), ('Usha'),
  ('Orient'), ('Kenstar'), ('Dell'), ('HP'), ('Lenovo'),
  ('ASUS'), ('Acer'), ('Apple'), ('MSI'), ('Microsoft'),
  ('Razer'), ('Xiaomi'), ('OnePlus'), ('Oppo'), ('Vivo'),
  ('Realme'), ('Motorola'), ('Google'), ('Nothing'),
  ('TCL'), ('Hisense'), ('Philips'), ('Sharp'), ('Toshiba'),
  ('Fujitsu'), ('ViewSonic'), ('BenQ'), ('AOC'), ('Gigabyte'),
  ('Luminous'), ('Microtek'), ('Exide'), ('Amaron'), ('Su-Kam'),
  ('Genus'), ('Okaya'), ('Base'), ('Livguard')
on conflict (name) do nothing;